apiVersion: skaffold/v4beta7
kind: Config

profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - ../../k8s/overlays/dev

  - name: staging
    manifests:
      kustomize:
        paths:
          - ../../k8s/overlays/staging
deploy:
  kubectl: {}
